import "./globals.css";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Separator } from "@/components/ui/separator";
import { i18n } from "@/config/i18n.config";
import TanstackProvider from "@/providers/tanstack-provider";
import ThemesProvider from "@/providers/theme-provider";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "alejunior.dev",
  description: "Generated by Alexandre Junior",
};

export async function generateStaticParams() {
  const languages = i18n.locales.map((lang) => ({ lang }));
  return languages;
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body className={jetBrainsMono.className}>
        <ThemesProvider>
          <Header />
          <Separator className="my-4" />

          <TanstackProvider>
            <main className="mx-auto max-w-5xl flex-col items-center justify-center  px-5 py-8 xl:px-0">
              {children}
            </main>
          </TanstackProvider>

          <Footer />
        </ThemesProvider>
      </body>
    </html>
  );
}
